# Generated by Django 5.1 on 2024-09-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0002_remove_fooditem_pic_path_fooditem_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/food_items'),
        ),
    ]
