# Generated by Django 5.1 on 2024-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0003_alter_fooditem_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='food_items/'),
        ),
    ]
