# Generated by Django 3.2.25 on 2024-09-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_num',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
