# Generated by Django 5.1 on 2024-09-09 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0004_alter_fooditem_picture'),
        ('menu', '0003_rename_category_menu_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.AddField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='food_items',
            field=models.ManyToManyField(to='fooditems.fooditem'),
        ),
    ]
