# Generated by Django 5.1 on 2024-09-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menuitem_category_remove_menu_description_and_more'),
        ('order', '0002_alter_orderitem_menu_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
