# Generated by Django 5.1 on 2024-09-10 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0004_alter_fooditem_picture'),
        ('order', '0002_alter_orderitem_menu_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu_item',
            new_name='menu',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='food_item',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='fooditems.fooditem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
